---
layout: post
title:  동기, 비동기 - Promise
date:   2021-06-21 15:01:35 +0300
image:  https://user-images.githubusercontent.com/77090941/119234172-69717180-bb67-11eb-8acc-f687aa97de80.jpg
tags:   Style
---
* link : https://www.youtube.com/watch?v=aoQSOZfz3vQ
### Promise
* 프로미스는 js에서 제공하는 비동기 코드를 간편하게 처리할 수 있도록 도와주는 object 이다.
* 프로미스는 어떤 기능을 실행하고 나서 정상적으로 동작하면, 성공의 메세지와 함께 처리된 결과값을 전달해줍니다. 그러나 기능을 수행하다 예상치 못한 문데가 발생하면 error를 전달해 준다.
* State: pending- fulfilled or rejected
* produce vs Consumer

1. Procuce(생산자)
  * 새 Promise가 생성되면 executor라는 콜백함수가 자동으로 실행됩니다.
```js
const promise = new Promise((resolve, reject)=>{
    //시간이 오래 걸리는 무거운 처리(network, read files..)
    console.log("doing something...");
    setTimeout(()=>{
        resolve("ellie"); // 성공
        // reject(new Error("no network")); 실패하면
    }, 2000)
});
``` 

2. Consumer
 * then, catch, finally
```js
promise
.then((value)=>{
    console.log(value);
})
.catch(error =>{
    console.log(error);
})
.finally(()=>{      // 성공하든 실패하든 마지막에 실행됨
    console.log("finally");
})
```

3. Promise chaining
   * then은 값을 바로 전달 할 수 도 있고, 리턴으로 Promise를 전달해도 된다.
```js
const fetchNumber = new Promise((resolve, reject)=>{
    setTimeout(()=> resolve(1), 1000);
});

fetchNumber
.then(num =>{
    return num*2; // 2
})
.then(num => num*3) // 6
.then (num =>{ //5
return new Promise((resolve, reject) =>{
    setTimeout(()=> resolve(num -1), 1000);
});
})
.then(num => console.log(num)); // 5
```
4. Error handling
   * catch로 error를 헨들링 할 수 있다. 
   * error가 발생해도 catch를 이용하면 전체적인 Promise 체인에 문제가 발행하지 않도록 만들 수 있다.
  ```js
  const getHen=()=>{
      return new Promise((resolve, reject)=>{
          setTimeout(()=>resolve("chicken"), 1000)
          // setTimeout(()=> reject(new Error("error!")), 1000);
      });
  };

  const getEgg = hen =>{
      new Promise((resolve, reject)=>{
          //setTimeout(()=> resolve(`${hen} =>Egg`), 1000);
          setTimeout(()=> reject(new Error(`error! ${hen} => Egg`)), 1000);
      });
  }
  const cook = (egg)=>{
      new Promise((resolve, reject)=>{
          setTimeout(() =>resolve(`${egg}=> chickReg`), 1000);
          //setTimeout(() =>resolve(new Error(`${egg}=> chickReg`)), 1000);
      });
  }

  getHen()
  .catch(error =>{
      console.log(error);
      return "0"; 
  })
  .then(hen => getEgg(hen))
  .catch(error=>{
      console.log(error);
      return "0"
  })
  .then(egg => cook(egg))
  .catch(error =>{
      console.log(error);
      return "0"
  })
  .then(result => console.log(result))
  .catch(error =>{
      console.log(error);
  })

   // 정직한 코드 
   // getHen()
   // .then((hen) => {
   //     return getEgg(hen);
   // })
   // .then((egg)=>{
   //     return cook(egg);
   // })
   // .then((result) =>{
   //     console.log(result);
   // })

   // 파라미터가 1개일때 함수이름만 쓰면, 암묵적으로 함수의 매개변수로 전달 됨.
    // getHen()
     //   .then(getEgg)
     //   .then(cook)
     //   .then(console.log); 
  ```

  5. callback to promise
   * 콜백 지옥 코드 수정
   * 콜백함수를 인자로 전달 안해도 됨!!
```js
"use strict"

class UserStorage {
    loginUser(id, password) {
        return new Promise((resolve, reject) =>{
            setTimeout(()=>{
                if(
                    (id === "ellie" && password === "123") ||
                    (id === "gunwoo" && password === "1104")
                ){
                    resolve(id);
                }else{
                    reject(new Error(`not found`));
                }
            }, 2000)
        });
    }


getRoles(user) {
    return new Promise((resolve, reject)=>{
        setTimeout(()=> {
            if(user === `ellie`) resolve({ name: "ellie", role:`admin`});
            else reject(new Error(`no access`));
        }, 1000);
    });
}
}

const id = prompt("enter your id");
const password = prompt(`enter your password`);

const userStorage = new UserStorage();
userStorage // 
    .loginUser(id, password)
    .then(user => userStorage.getRole(user))
    .then(userInfo => alert(`name: ${userInfo.name}, role: ${userInfo.role}`))
    .catch(error => console.log(error));
```